/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Crop = IDL.Record({
  'id' : IDL.Nat,
  'cultivationPractices' : IDL.Text,
  'farm' : IDL.Nat,
  'name' : IDL.Text,
  'harvestingYields' : IDL.Text,
  'lastHarvest' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'areaHa' : IDL.Float64,
  'image' : IDL.Opt(IDL.Text),
  'pestsDiseases' : IDL.Text,
});
export const FarmStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Farm = IDL.Record({
  'id' : IDL.Nat,
  'status' : FarmStatus,
  'manager' : IDL.Text,
  'name' : IDL.Text,
  'totalAreaHa' : IDL.Float64,
  'keyCrops' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const InventoryStatus = IDL.Variant({
  'inStock' : IDL.Null,
  'critical' : IDL.Null,
  'lowStock' : IDL.Null,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : InventoryStatus,
  'threshold' : IDL.Float64,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'quantity' : IDL.Float64,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'processed' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Stage = IDL.Variant({
  'growing' : IDL.Null,
  'harvesting' : IDL.Null,
  'planting' : IDL.Null,
});
export const ProductionCycle = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'endDate' : IDL.Opt(IDL.Int),
  'crop' : IDL.Text,
  'farmField' : IDL.Text,
  'stage' : Stage,
  'areaHa' : IDL.Float64,
  'startDate' : IDL.Int,
  'expectedYield' : IDL.Float64,
});
export const ReportStatus = IDL.Variant({
  'saved' : IDL.Null,
  'generated' : IDL.Null,
});
export const ReportType = IDL.Variant({
  'soil' : IDL.Null,
  'market' : IDL.Null,
  'fieldActivity' : IDL.Null,
  'yield' : IDL.Null,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReportStatus,
  'name' : IDL.Text,
  'reportType' : ReportType,
  'locationFarm' : IDL.Text,
  'generatedDate' : IDL.Int,
});
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'crop' : IDL.Text,
  'date' : IDL.Int,
  'farm' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'quantity' : IDL.Float64,
  'buyer' : IDL.Text,
  'unitPrice' : IDL.Float64,
});
export const SupportStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const SupportPriority = IDL.Variant({
  'important' : IDL.Null,
  'urgent' : IDL.Null,
});
export const SupportRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : SupportStatus,
  'subject' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'priority' : SupportPriority,
  'attachments' : IDL.Vec(IDL.Text),
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ArticleStatus = IDL.Variant({
  'pendingReview' : IDL.Null,
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const RegionalFocus = IDL.Variant({
  'sadc' : IDL.Null,
  'global' : IDL.Null,
  'malawi' : IDL.Null,
});
export const NewsArticle = IDL.Record({
  'id' : IDL.Nat,
  'status' : ArticleStatus,
  'featuredOnPage' : IDL.Vec(IDL.Text),
  'body' : IDL.Text,
  'headline' : IDL.Text,
  'createdAt' : IDL.Int,
  'regionalFocus' : RegionalFocus,
  'tags' : IDL.Vec(IDL.Text),
  'relatedCrops' : IDL.Vec(IDL.Text),
  'scheduledPublishDate' : IDL.Opt(IDL.Int),
  'subHeadline' : IDL.Text,
  'bannerImage' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addCrop' : IDL.Func([Crop], [IDL.Nat], []),
  'addFarm' : IDL.Func([Farm], [IDL.Nat], []),
  'addInventoryItem' : IDL.Func([InventoryItem], [IDL.Nat], []),
  'addPayment' : IDL.Func([Payment], [IDL.Nat], []),
  'addProductionCycle' : IDL.Func([ProductionCycle], [IDL.Nat], []),
  'addReport' : IDL.Func([Report], [IDL.Nat], []),
  'addSale' : IDL.Func([Sale], [IDL.Nat], []),
  'addSupportRequest' : IDL.Func([SupportRequest], [IDL.Nat], []),
  'addUser' : IDL.Func([User], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNewsArticle' : IDL.Func([NewsArticle], [IDL.Nat], []),
  'deleteCrop' : IDL.Func([IDL.Nat], [], []),
  'deleteFarm' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCrop' : IDL.Func([IDL.Nat], [IDL.Opt(Crop)], ['query']),
  'getFarm' : IDL.Func([IDL.Nat], [IDL.Opt(Farm)], ['query']),
  'getInventoryItem' : IDL.Func([IDL.Nat], [IDL.Opt(InventoryItem)], ['query']),
  'getNewsArticle' : IDL.Func([IDL.Nat], [IDL.Opt(NewsArticle)], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
  'getProductionCycle' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ProductionCycle)],
      ['query'],
    ),
  'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
  'getSale' : IDL.Func([IDL.Nat], [IDL.Opt(Sale)], ['query']),
  'getSupportRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SupportRequest)],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
  'listFarms' : IDL.Func([], [IDL.Vec(Farm)], ['query']),
  'listInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'listNewsArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'listPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'listProductionCycles' : IDL.Func([], [IDL.Vec(ProductionCycle)], ['query']),
  'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'listSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'listSupportRequests' : IDL.Func([], [IDL.Vec(SupportRequest)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateCrop' : IDL.Func([Crop], [], []),
  'updateFarm' : IDL.Func([Farm], [], []),
  'updateNewsArticle' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        RegionalFocus,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        ArticleStatus,
        IDL.Opt(IDL.Int),
        IDL.Text,
      ],
      [IDL.Opt(NewsArticle)],
      [],
    ),
  'updateNewsArticleStatus' : IDL.Func(
      [IDL.Nat, ArticleStatus],
      [IDL.Opt(NewsArticle)],
      [],
    ),
  'updatePayment' : IDL.Func([Payment], [], []),
  'updateProductionCycle' : IDL.Func([ProductionCycle], [], []),
  'updateReport' : IDL.Func([Report], [], []),
  'updateSale' : IDL.Func([Sale], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Crop = IDL.Record({
    'id' : IDL.Nat,
    'cultivationPractices' : IDL.Text,
    'farm' : IDL.Nat,
    'name' : IDL.Text,
    'harvestingYields' : IDL.Text,
    'lastHarvest' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'areaHa' : IDL.Float64,
    'image' : IDL.Opt(IDL.Text),
    'pestsDiseases' : IDL.Text,
  });
  const FarmStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Farm = IDL.Record({
    'id' : IDL.Nat,
    'status' : FarmStatus,
    'manager' : IDL.Text,
    'name' : IDL.Text,
    'totalAreaHa' : IDL.Float64,
    'keyCrops' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const InventoryStatus = IDL.Variant({
    'inStock' : IDL.Null,
    'critical' : IDL.Null,
    'lowStock' : IDL.Null,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : InventoryStatus,
    'threshold' : IDL.Float64,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'quantity' : IDL.Float64,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'processed' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Stage = IDL.Variant({
    'growing' : IDL.Null,
    'harvesting' : IDL.Null,
    'planting' : IDL.Null,
  });
  const ProductionCycle = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'endDate' : IDL.Opt(IDL.Int),
    'crop' : IDL.Text,
    'farmField' : IDL.Text,
    'stage' : Stage,
    'areaHa' : IDL.Float64,
    'startDate' : IDL.Int,
    'expectedYield' : IDL.Float64,
  });
  const ReportStatus = IDL.Variant({
    'saved' : IDL.Null,
    'generated' : IDL.Null,
  });
  const ReportType = IDL.Variant({
    'soil' : IDL.Null,
    'market' : IDL.Null,
    'fieldActivity' : IDL.Null,
    'yield' : IDL.Null,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReportStatus,
    'name' : IDL.Text,
    'reportType' : ReportType,
    'locationFarm' : IDL.Text,
    'generatedDate' : IDL.Int,
  });
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'crop' : IDL.Text,
    'date' : IDL.Int,
    'farm' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'quantity' : IDL.Float64,
    'buyer' : IDL.Text,
    'unitPrice' : IDL.Float64,
  });
  const SupportStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const SupportPriority = IDL.Variant({
    'important' : IDL.Null,
    'urgent' : IDL.Null,
  });
  const SupportRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : SupportStatus,
    'subject' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'priority' : SupportPriority,
    'attachments' : IDL.Vec(IDL.Text),
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ArticleStatus = IDL.Variant({
    'pendingReview' : IDL.Null,
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const RegionalFocus = IDL.Variant({
    'sadc' : IDL.Null,
    'global' : IDL.Null,
    'malawi' : IDL.Null,
  });
  const NewsArticle = IDL.Record({
    'id' : IDL.Nat,
    'status' : ArticleStatus,
    'featuredOnPage' : IDL.Vec(IDL.Text),
    'body' : IDL.Text,
    'headline' : IDL.Text,
    'createdAt' : IDL.Int,
    'regionalFocus' : RegionalFocus,
    'tags' : IDL.Vec(IDL.Text),
    'relatedCrops' : IDL.Vec(IDL.Text),
    'scheduledPublishDate' : IDL.Opt(IDL.Int),
    'subHeadline' : IDL.Text,
    'bannerImage' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addCrop' : IDL.Func([Crop], [IDL.Nat], []),
    'addFarm' : IDL.Func([Farm], [IDL.Nat], []),
    'addInventoryItem' : IDL.Func([InventoryItem], [IDL.Nat], []),
    'addPayment' : IDL.Func([Payment], [IDL.Nat], []),
    'addProductionCycle' : IDL.Func([ProductionCycle], [IDL.Nat], []),
    'addReport' : IDL.Func([Report], [IDL.Nat], []),
    'addSale' : IDL.Func([Sale], [IDL.Nat], []),
    'addSupportRequest' : IDL.Func([SupportRequest], [IDL.Nat], []),
    'addUser' : IDL.Func([User], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNewsArticle' : IDL.Func([NewsArticle], [IDL.Nat], []),
    'deleteCrop' : IDL.Func([IDL.Nat], [], []),
    'deleteFarm' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCrop' : IDL.Func([IDL.Nat], [IDL.Opt(Crop)], ['query']),
    'getFarm' : IDL.Func([IDL.Nat], [IDL.Opt(Farm)], ['query']),
    'getInventoryItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(InventoryItem)],
        ['query'],
      ),
    'getNewsArticle' : IDL.Func([IDL.Nat], [IDL.Opt(NewsArticle)], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
    'getProductionCycle' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProductionCycle)],
        ['query'],
      ),
    'getReport' : IDL.Func([IDL.Nat], [IDL.Opt(Report)], ['query']),
    'getSale' : IDL.Func([IDL.Nat], [IDL.Opt(Sale)], ['query']),
    'getSupportRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SupportRequest)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCrops' : IDL.Func([], [IDL.Vec(Crop)], ['query']),
    'listFarms' : IDL.Func([], [IDL.Vec(Farm)], ['query']),
    'listInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'listNewsArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'listPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'listProductionCycles' : IDL.Func(
        [],
        [IDL.Vec(ProductionCycle)],
        ['query'],
      ),
    'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'listSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'listSupportRequests' : IDL.Func([], [IDL.Vec(SupportRequest)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateCrop' : IDL.Func([Crop], [], []),
    'updateFarm' : IDL.Func([Farm], [], []),
    'updateNewsArticle' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          RegionalFocus,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          ArticleStatus,
          IDL.Opt(IDL.Int),
          IDL.Text,
        ],
        [IDL.Opt(NewsArticle)],
        [],
      ),
    'updateNewsArticleStatus' : IDL.Func(
        [IDL.Nat, ArticleStatus],
        [IDL.Opt(NewsArticle)],
        [],
      ),
    'updatePayment' : IDL.Func([Payment], [], []),
    'updateProductionCycle' : IDL.Func([ProductionCycle], [], []),
    'updateReport' : IDL.Func([Report], [], []),
    'updateSale' : IDL.Func([Sale], [], []),
  });
};

export const init = ({ IDL }) => { return []; };