/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ArticleStatus = { 'pendingReview' : null } |
  { 'published' : null } |
  { 'draft' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Crop {
  'id' : bigint,
  'cultivationPractices' : string,
  'farm' : bigint,
  'name' : string,
  'harvestingYields' : string,
  'lastHarvest' : [] | [bigint],
  'description' : string,
  'areaHa' : number,
  'image' : [] | [string],
  'pestsDiseases' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Farm {
  'id' : bigint,
  'status' : FarmStatus,
  'manager' : string,
  'name' : string,
  'totalAreaHa' : number,
  'keyCrops' : Array<string>,
  'location' : string,
}
export type FarmStatus = { 'active' : null } |
  { 'inactive' : null };
export interface InventoryItem {
  'id' : bigint,
  'status' : InventoryStatus,
  'threshold' : number,
  'name' : string,
  'unit' : string,
  'quantity' : number,
}
export type InventoryStatus = { 'inStock' : null } |
  { 'critical' : null } |
  { 'lowStock' : null };
export interface NewsArticle {
  'id' : bigint,
  'status' : ArticleStatus,
  'featuredOnPage' : Array<string>,
  'body' : string,
  'headline' : string,
  'createdAt' : bigint,
  'regionalFocus' : RegionalFocus,
  'tags' : Array<string>,
  'relatedCrops' : Array<string>,
  'scheduledPublishDate' : [] | [bigint],
  'subHeadline' : string,
  'bannerImage' : string,
}
export interface Payment {
  'id' : bigint,
  'status' : PaymentStatus,
  'date' : bigint,
  'description' : string,
  'amount' : number,
}
export type PaymentStatus = { 'pending' : null } |
  { 'processed' : null };
export interface ProductionCycle {
  'id' : bigint,
  'status' : string,
  'endDate' : [] | [bigint],
  'crop' : string,
  'farmField' : string,
  'stage' : Stage,
  'areaHa' : number,
  'startDate' : bigint,
  'expectedYield' : number,
}
export type RegionalFocus = { 'sadc' : null } |
  { 'global' : null } |
  { 'malawi' : null };
export interface Report {
  'id' : bigint,
  'status' : ReportStatus,
  'name' : string,
  'reportType' : ReportType,
  'locationFarm' : string,
  'generatedDate' : bigint,
}
export type ReportStatus = { 'saved' : null } |
  { 'generated' : null };
export type ReportType = { 'soil' : null } |
  { 'market' : null } |
  { 'fieldActivity' : null } |
  { 'yield' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Sale {
  'id' : bigint,
  'crop' : string,
  'date' : bigint,
  'farm' : string,
  'totalAmount' : number,
  'quantity' : number,
  'buyer' : string,
  'unitPrice' : number,
}
export type Stage = { 'growing' : null } |
  { 'harvesting' : null } |
  { 'planting' : null };
export type SupportPriority = { 'important' : null } |
  { 'urgent' : null };
export interface SupportRequest {
  'id' : bigint,
  'status' : SupportStatus,
  'subject' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
  'priority' : SupportPriority,
  'attachments' : Array<string>,
}
export type SupportStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export interface User {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addCrop' : ActorMethod<[Crop], bigint>,
  'addFarm' : ActorMethod<[Farm], bigint>,
  'addInventoryItem' : ActorMethod<[InventoryItem], bigint>,
  'addPayment' : ActorMethod<[Payment], bigint>,
  'addProductionCycle' : ActorMethod<[ProductionCycle], bigint>,
  'addReport' : ActorMethod<[Report], bigint>,
  'addSale' : ActorMethod<[Sale], bigint>,
  'addSupportRequest' : ActorMethod<[SupportRequest], bigint>,
  'addUser' : ActorMethod<[User], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNewsArticle' : ActorMethod<[NewsArticle], bigint>,
  'deleteCrop' : ActorMethod<[bigint], undefined>,
  'deleteFarm' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCrop' : ActorMethod<[bigint], [] | [Crop]>,
  'getFarm' : ActorMethod<[bigint], [] | [Farm]>,
  'getInventoryItem' : ActorMethod<[bigint], [] | [InventoryItem]>,
  'getNewsArticle' : ActorMethod<[bigint], [] | [NewsArticle]>,
  'getPayment' : ActorMethod<[bigint], [] | [Payment]>,
  'getProductionCycle' : ActorMethod<[bigint], [] | [ProductionCycle]>,
  'getReport' : ActorMethod<[bigint], [] | [Report]>,
  'getSale' : ActorMethod<[bigint], [] | [Sale]>,
  'getSupportRequest' : ActorMethod<[bigint], [] | [SupportRequest]>,
  'getUser' : ActorMethod<[bigint], [] | [User]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCrops' : ActorMethod<[], Array<Crop>>,
  'listFarms' : ActorMethod<[], Array<Farm>>,
  'listInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'listNewsArticles' : ActorMethod<[], Array<NewsArticle>>,
  'listPayments' : ActorMethod<[], Array<Payment>>,
  'listProductionCycles' : ActorMethod<[], Array<ProductionCycle>>,
  'listReports' : ActorMethod<[], Array<Report>>,
  'listSales' : ActorMethod<[], Array<Sale>>,
  'listSupportRequests' : ActorMethod<[], Array<SupportRequest>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'schema' : ActorMethod<[], string>,
  'updateCrop' : ActorMethod<[Crop], undefined>,
  'updateFarm' : ActorMethod<[Farm], undefined>,
  'updateNewsArticle' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      RegionalFocus,
      Array<string>,
      Array<string>,
      ArticleStatus,
      [] | [bigint],
      string,
    ],
    [] | [NewsArticle]
  >,
  'updateNewsArticleStatus' : ActorMethod<
    [bigint, ArticleStatus],
    [] | [NewsArticle]
  >,
  'updatePayment' : ActorMethod<[Payment], undefined>,
  'updateProductionCycle' : ActorMethod<[ProductionCycle], undefined>,
  'updateReport' : ActorMethod<[Report], undefined>,
  'updateSale' : ActorMethod<[Sale], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];