/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Report {
    id: bigint;
    status: ReportStatus;
    name: string;
    reportType: ReportType;
    locationFarm: string;
    generatedDate: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface InventoryItem {
    id: bigint;
    status: InventoryStatus;
    threshold: number;
    name: string;
    unit: string;
    quantity: number;
}
export interface ProductionCycle {
    id: bigint;
    status: string;
    endDate?: bigint;
    crop: string;
    farmField: string;
    stage: Stage;
    areaHa: number;
    startDate: bigint;
    expectedYield: number;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface Farm {
    id: bigint;
    status: FarmStatus;
    manager: string;
    name: string;
    totalAreaHa: number;
    keyCrops: Array<string>;
    location: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface User {
    id: bigint;
    name: string;
    role: string;
    email: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Crop {
    id: bigint;
    cultivationPractices: string;
    farm: bigint;
    name: string;
    harvestingYields: string;
    lastHarvest?: bigint;
    description: string;
    areaHa: number;
    image?: string;
    pestsDiseases: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Payment {
    id: bigint;
    status: PaymentStatus;
    date: bigint;
    description: string;
    amount: number;
}
export interface Sale {
    id: bigint;
    crop: string;
    date: bigint;
    farm: string;
    totalAmount: number;
    quantity: number;
    buyer: string;
    unitPrice: number;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface SupportRequest {
    id: bigint;
    status: SupportStatus;
    subject: string;
    createdAt: bigint;
    description: string;
    category: string;
    priority: SupportPriority;
    attachments: Array<string>;
}
export interface NewsArticle {
    id: bigint;
    status: ArticleStatus;
    featuredOnPage: Array<string>;
    body: string;
    headline: string;
    createdAt: bigint;
    regionalFocus: RegionalFocus;
    tags: Array<string>;
    relatedCrops: Array<string>;
    scheduledPublishDate?: bigint;
    subHeadline: string;
    bannerImage: string;
}
export enum ArticleStatus {
    pendingReview = "pendingReview",
    published = "published",
    draft = "draft"
}
export enum FarmStatus {
    active = "active",
    inactive = "inactive"
}
export enum InventoryStatus {
    inStock = "inStock",
    critical = "critical",
    lowStock = "lowStock"
}
export enum PaymentStatus {
    pending = "pending",
    processed = "processed"
}
export enum RegionalFocus {
    sadc = "sadc",
    global = "global",
    malawi = "malawi"
}
export enum ReportStatus {
    saved = "saved",
    generated = "generated"
}
export enum ReportType {
    soil = "soil",
    market = "market",
    fieldActivity = "fieldActivity",
    yield_ = "yield"
}
export enum Stage {
    growing = "growing",
    harvesting = "harvesting",
    planting = "planting"
}
export enum SupportPriority {
    important = "important",
    urgent = "urgent"
}
export enum SupportStatus {
    resolved = "resolved",
    closed = "closed",
    open = "open",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addCrop(crop: Crop): Promise<bigint>;
    addFarm(farm: Farm): Promise<bigint>;
    addInventoryItem(item: InventoryItem): Promise<bigint>;
    addPayment(payment: Payment): Promise<bigint>;
    addProductionCycle(cycle: ProductionCycle): Promise<bigint>;
    addReport(report: Report): Promise<bigint>;
    addSale(sale: Sale): Promise<bigint>;
    addSupportRequest(request: SupportRequest): Promise<bigint>;
    addUser(user: User): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createNewsArticle(article: NewsArticle): Promise<bigint>;
    deleteCrop(id: bigint): Promise<void>;
    deleteFarm(id: bigint): Promise<void>;
    execute(qJson: string): Promise<Result>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getCrop(id: bigint): Promise<Crop | null>;
    getFarm(id: bigint): Promise<Farm | null>;
    getInventoryItem(id: bigint): Promise<InventoryItem | null>;
    getNewsArticle(id: bigint): Promise<NewsArticle | null>;
    getPayment(id: bigint): Promise<Payment | null>;
    getProductionCycle(id: bigint): Promise<ProductionCycle | null>;
    getReport(id: bigint): Promise<Report | null>;
    getSale(id: bigint): Promise<Sale | null>;
    getSupportRequest(id: bigint): Promise<SupportRequest | null>;
    getUser(id: bigint): Promise<User | null>;
    isCallerAdmin(): Promise<boolean>;
    listCrops(): Promise<Array<Crop>>;
    listFarms(): Promise<Array<Farm>>;
    listInventoryItems(): Promise<Array<InventoryItem>>;
    listNewsArticles(): Promise<Array<NewsArticle>>;
    listPayments(): Promise<Array<Payment>>;
    listProductionCycles(): Promise<Array<ProductionCycle>>;
    listReports(): Promise<Array<Report>>;
    listSales(): Promise<Array<Sale>>;
    listSupportRequests(): Promise<Array<SupportRequest>>;
    listUsers(): Promise<Array<User>>;
    schema(): Promise<string>;
    updateCrop(crop: Crop): Promise<void>;
    updateFarm(farm: Farm): Promise<void>;
    updateNewsArticle(id: bigint, headline: string, subHeadline: string, body: string, regionalFocus: RegionalFocus, relatedCrops: Array<string>, tags: Array<string>, status: ArticleStatus, scheduledPublishDate: bigint | null, bannerImage: string): Promise<NewsArticle | null>;
    updateNewsArticleStatus(id: bigint, status: ArticleStatus): Promise<NewsArticle | null>;
    updatePayment(payment: Payment): Promise<void>;
    updateProductionCycle(cycle: ProductionCycle): Promise<void>;
    updateReport(report: Report): Promise<void>;
    updateSale(sale: Sale): Promise<void>;
}
import type { ArticleStatus as _ArticleStatus, Cell as _Cell, Crop as _Crop, Error as _Error, Farm as _Farm, FarmStatus as _FarmStatus, InventoryItem as _InventoryItem, InventoryStatus as _InventoryStatus, NewsArticle as _NewsArticle, Payment as _Payment, PaymentStatus as _PaymentStatus, ProductionCycle as _ProductionCycle, RegionalFocus as _RegionalFocus, Report as _Report, ReportStatus as _ReportStatus, ReportType as _ReportType, Result as _Result, Result__1 as _Result__1, Sale as _Sale, Stage as _Stage, SupportPriority as _SupportPriority, SupportRequest as _SupportRequest, SupportStatus as _SupportStatus, User as _User, UserRole as _UserRole, Value as _Value, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addCrop(arg0: Crop): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCrop(to_candid_Crop_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCrop(to_candid_Crop_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addFarm(arg0: Farm): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFarm(to_candid_Farm_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFarm(to_candid_Farm_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addInventoryItem(arg0: InventoryItem): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(to_candid_InventoryItem_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(to_candid_InventoryItem_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPayment(arg0: Payment): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(to_candid_Payment_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(to_candid_Payment_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProductionCycle(arg0: ProductionCycle): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductionCycle(to_candid_ProductionCycle_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductionCycle(to_candid_ProductionCycle_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addReport(arg0: Report): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addReport(to_candid_Report_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReport(to_candid_Report_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSale(arg0: Sale): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSale(arg0);
            return result;
        }
    }
    async addSupportRequest(arg0: SupportRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupportRequest(to_candid_SupportRequest_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupportRequest(to_candid_SupportRequest_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addUser(arg0: User): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createNewsArticle(arg0: NewsArticle): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNewsArticle(to_candid_NewsArticle_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNewsArticle(to_candid_NewsArticle_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCrop(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCrop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCrop(arg0);
            return result;
        }
    }
    async deleteFarm(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFarm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFarm(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCrop(arg0: bigint): Promise<Crop | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrop(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrop(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarm(arg0: bigint): Promise<Farm | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarm(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarm(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryItem(arg0: bigint): Promise<InventoryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItem(arg0);
                return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItem(arg0);
            return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsArticle(arg0: bigint): Promise<NewsArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsArticle(arg0);
                return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsArticle(arg0);
            return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: bigint): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductionCycle(arg0: bigint): Promise<ProductionCycle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionCycle(arg0);
                return from_candid_opt_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionCycle(arg0);
            return from_candid_opt_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: bigint): Promise<Report | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n92(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n92(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSale(arg0: bigint): Promise<Sale | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSale(arg0);
                return from_candid_opt_n99(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSale(arg0);
            return from_candid_opt_n99(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupportRequest(arg0: bigint): Promise<SupportRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportRequest(arg0);
                return from_candid_opt_n100(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportRequest(arg0);
            return from_candid_opt_n100(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: bigint): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n107(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n107(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCrops(): Promise<Array<Crop>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCrops();
                return from_candid_vec_n108(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCrops();
            return from_candid_vec_n108(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFarms(): Promise<Array<Farm>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFarms();
                return from_candid_vec_n109(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFarms();
            return from_candid_vec_n109(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInventoryItems();
                return from_candid_vec_n110(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInventoryItems();
            return from_candid_vec_n110(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNewsArticles(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNewsArticles();
                return from_candid_vec_n111(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNewsArticles();
            return from_candid_vec_n111(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPayments();
                return from_candid_vec_n112(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPayments();
            return from_candid_vec_n112(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProductionCycles(): Promise<Array<ProductionCycle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductionCycles();
                return from_candid_vec_n113(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductionCycles();
            return from_candid_vec_n113(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReports();
                return from_candid_vec_n114(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReports();
            return from_candid_vec_n114(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSales();
            return result;
        }
    }
    async listSupportRequests(): Promise<Array<SupportRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSupportRequests();
                return from_candid_vec_n115(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSupportRequests();
            return from_candid_vec_n115(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateCrop(arg0: Crop): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCrop(to_candid_Crop_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCrop(to_candid_Crop_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateFarm(arg0: Farm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFarm(to_candid_Farm_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFarm(to_candid_Farm_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateNewsArticle(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: RegionalFocus, arg5: Array<string>, arg6: Array<string>, arg7: ArticleStatus, arg8: bigint | null, arg9: string): Promise<NewsArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsArticle(arg0, arg1, arg2, arg3, to_candid_RegionalFocus_n48(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_ArticleStatus_n46(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n116(this._uploadFile, this._downloadFile, arg8), arg9);
                return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsArticle(arg0, arg1, arg2, arg3, to_candid_RegionalFocus_n48(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_ArticleStatus_n46(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n116(this._uploadFile, this._downloadFile, arg8), arg9);
            return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNewsArticleStatus(arg0: bigint, arg1: ArticleStatus): Promise<NewsArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsArticleStatus(arg0, to_candid_ArticleStatus_n46(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsArticleStatus(arg0, to_candid_ArticleStatus_n46(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePayment(arg0: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(to_candid_Payment_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(to_candid_Payment_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProductionCycle(arg0: ProductionCycle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductionCycle(to_candid_ProductionCycle_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductionCycle(to_candid_ProductionCycle_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateReport(arg0: Report): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReport(to_candid_Report_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReport(to_candid_Report_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSale(arg0: Sale): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSale(arg0);
            return result;
        }
    }
}
function from_candid_ArticleStatus_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArticleStatus): ArticleStatus {
    return from_candid_variant_n79(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Crop_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Crop): Crop {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_FarmStatus_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FarmStatus): FarmStatus {
    return from_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function from_candid_Farm_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Farm): Farm {
    return from_candid_record_n67(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryItem_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryItem): InventoryItem {
    return from_candid_record_n72(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryStatus_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryStatus): InventoryStatus {
    return from_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function from_candid_NewsArticle_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsArticle): NewsArticle {
    return from_candid_record_n77(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n86(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n84(_uploadFile, _downloadFile, value);
}
function from_candid_ProductionCycle_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductionCycle): ProductionCycle {
    return from_candid_record_n89(_uploadFile, _downloadFile, value);
}
function from_candid_RegionalFocus_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegionalFocus): RegionalFocus {
    return from_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n96(_uploadFile, _downloadFile, value);
}
function from_candid_ReportType_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportType): ReportType {
    return from_candid_variant_n98(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n94(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Stage_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stage): Stage {
    return from_candid_variant_n91(_uploadFile, _downloadFile, value);
}
function from_candid_SupportPriority_n105(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupportPriority): SupportPriority {
    return from_candid_variant_n106(_uploadFile, _downloadFile, value);
}
function from_candid_SupportRequest_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupportRequest): SupportRequest {
    return from_candid_record_n102(_uploadFile, _downloadFile, value);
}
function from_candid_SupportStatus_n103(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupportStatus): SupportStatus {
    return from_candid_variant_n104(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupportRequest]): SupportRequest | null {
    return value.length === 0 ? null : from_candid_SupportRequest_n101(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n107(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Crop]): Crop | null {
    return value.length === 0 ? null : from_candid_Crop_n61(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Farm]): Farm | null {
    return value.length === 0 ? null : from_candid_Farm_n66(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InventoryItem]): InventoryItem | null {
    return value.length === 0 ? null : from_candid_InventoryItem_n71(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewsArticle]): NewsArticle | null {
    return value.length === 0 ? null : from_candid_NewsArticle_n76(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n83(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductionCycle]): ProductionCycle | null {
    return value.length === 0 ? null : from_candid_ProductionCycle_n88(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Report]): Report | null {
    return value.length === 0 ? null : from_candid_Report_n93(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sale]): Sale | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n102(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SupportStatus;
    subject: string;
    createdAt: bigint;
    description: string;
    category: string;
    priority: _SupportPriority;
    attachments: Array<string>;
}): {
    id: bigint;
    status: SupportStatus;
    subject: string;
    createdAt: bigint;
    description: string;
    category: string;
    priority: SupportPriority;
    attachments: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_SupportStatus_n103(_uploadFile, _downloadFile, value.status),
        subject: value.subject,
        createdAt: value.createdAt,
        description: value.description,
        category: value.category,
        priority: from_candid_SupportPriority_n105(_uploadFile, _downloadFile, value.priority),
        attachments: value.attachments
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n52(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n56(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    cultivationPractices: string;
    farm: bigint;
    name: string;
    harvestingYields: string;
    lastHarvest: [] | [bigint];
    description: string;
    areaHa: number;
    image: [] | [string];
    pestsDiseases: string;
}): {
    id: bigint;
    cultivationPractices: string;
    farm: bigint;
    name: string;
    harvestingYields: string;
    lastHarvest?: bigint;
    description: string;
    areaHa: number;
    image?: string;
    pestsDiseases: string;
} {
    return {
        id: value.id,
        cultivationPractices: value.cultivationPractices,
        farm: value.farm,
        name: value.name,
        harvestingYields: value.harvestingYields,
        lastHarvest: record_opt_to_undefined(from_candid_opt_n63(_uploadFile, _downloadFile, value.lastHarvest)),
        description: value.description,
        areaHa: value.areaHa,
        image: record_opt_to_undefined(from_candid_opt_n64(_uploadFile, _downloadFile, value.image)),
        pestsDiseases: value.pestsDiseases
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _FarmStatus;
    manager: string;
    name: string;
    totalAreaHa: number;
    keyCrops: Array<string>;
    location: string;
}): {
    id: bigint;
    status: FarmStatus;
    manager: string;
    name: string;
    totalAreaHa: number;
    keyCrops: Array<string>;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_FarmStatus_n68(_uploadFile, _downloadFile, value.status),
        manager: value.manager,
        name: value.name,
        totalAreaHa: value.totalAreaHa,
        keyCrops: value.keyCrops,
        location: value.location
    };
}
function from_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InventoryStatus;
    threshold: number;
    name: string;
    unit: string;
    quantity: number;
}): {
    id: bigint;
    status: InventoryStatus;
    threshold: number;
    name: string;
    unit: string;
    quantity: number;
} {
    return {
        id: value.id,
        status: from_candid_InventoryStatus_n73(_uploadFile, _downloadFile, value.status),
        threshold: value.threshold,
        name: value.name,
        unit: value.unit,
        quantity: value.quantity
    };
}
function from_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ArticleStatus;
    featuredOnPage: Array<string>;
    body: string;
    headline: string;
    createdAt: bigint;
    regionalFocus: _RegionalFocus;
    tags: Array<string>;
    relatedCrops: Array<string>;
    scheduledPublishDate: [] | [bigint];
    subHeadline: string;
    bannerImage: string;
}): {
    id: bigint;
    status: ArticleStatus;
    featuredOnPage: Array<string>;
    body: string;
    headline: string;
    createdAt: bigint;
    regionalFocus: RegionalFocus;
    tags: Array<string>;
    relatedCrops: Array<string>;
    scheduledPublishDate?: bigint;
    subHeadline: string;
    bannerImage: string;
} {
    return {
        id: value.id,
        status: from_candid_ArticleStatus_n78(_uploadFile, _downloadFile, value.status),
        featuredOnPage: value.featuredOnPage,
        body: value.body,
        headline: value.headline,
        createdAt: value.createdAt,
        regionalFocus: from_candid_RegionalFocus_n80(_uploadFile, _downloadFile, value.regionalFocus),
        tags: value.tags,
        relatedCrops: value.relatedCrops,
        scheduledPublishDate: record_opt_to_undefined(from_candid_opt_n63(_uploadFile, _downloadFile, value.scheduledPublishDate)),
        subHeadline: value.subHeadline,
        bannerImage: value.bannerImage
    };
}
function from_candid_record_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentStatus;
    date: bigint;
    description: string;
    amount: number;
}): {
    id: bigint;
    status: PaymentStatus;
    date: bigint;
    description: string;
    amount: number;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n85(_uploadFile, _downloadFile, value.status),
        date: value.date,
        description: value.description,
        amount: value.amount
    };
}
function from_candid_record_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    endDate: [] | [bigint];
    crop: string;
    farmField: string;
    stage: _Stage;
    areaHa: number;
    startDate: bigint;
    expectedYield: number;
}): {
    id: bigint;
    status: string;
    endDate?: bigint;
    crop: string;
    farmField: string;
    stage: Stage;
    areaHa: number;
    startDate: bigint;
    expectedYield: number;
} {
    return {
        id: value.id,
        status: value.status,
        endDate: record_opt_to_undefined(from_candid_opt_n63(_uploadFile, _downloadFile, value.endDate)),
        crop: value.crop,
        farmField: value.farmField,
        stage: from_candid_Stage_n90(_uploadFile, _downloadFile, value.stage),
        areaHa: value.areaHa,
        startDate: value.startDate,
        expectedYield: value.expectedYield
    };
}
function from_candid_record_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ReportStatus;
    name: string;
    reportType: _ReportType;
    locationFarm: string;
    generatedDate: bigint;
}): {
    id: bigint;
    status: ReportStatus;
    name: string;
    reportType: ReportType;
    locationFarm: string;
    generatedDate: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ReportStatus_n95(_uploadFile, _downloadFile, value.status),
        name: value.name,
        reportType: from_candid_ReportType_n97(_uploadFile, _downloadFile, value.reportType),
        locationFarm: value.locationFarm,
        generatedDate: value.generatedDate
    };
}
function from_candid_variant_n104(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    closed: null;
} | {
    open: null;
} | {
    inProgress: null;
}): SupportStatus {
    return "resolved" in value ? SupportStatus.resolved : "closed" in value ? SupportStatus.closed : "open" in value ? SupportStatus.open : "inProgress" in value ? SupportStatus.inProgress : value;
}
function from_candid_variant_n106(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    important: null;
} | {
    urgent: null;
}): SupportPriority {
    return "important" in value ? SupportPriority.important : "urgent" in value ? SupportPriority.urgent : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): FarmStatus {
    return "active" in value ? FarmStatus.active : "inactive" in value ? FarmStatus.inactive : value;
}
function from_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStock: null;
} | {
    critical: null;
} | {
    lowStock: null;
}): InventoryStatus {
    return "inStock" in value ? InventoryStatus.inStock : "critical" in value ? InventoryStatus.critical : "lowStock" in value ? InventoryStatus.lowStock : value;
}
function from_candid_variant_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingReview: null;
} | {
    published: null;
} | {
    draft: null;
}): ArticleStatus {
    return "pendingReview" in value ? ArticleStatus.pendingReview : "published" in value ? ArticleStatus.published : "draft" in value ? ArticleStatus.draft : value;
}
function from_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sadc: null;
} | {
    global: null;
} | {
    malawi: null;
}): RegionalFocus {
    return "sadc" in value ? RegionalFocus.sadc : "global" in value ? RegionalFocus.global : "malawi" in value ? RegionalFocus.malawi : value;
}
function from_candid_variant_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    processed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "processed" in value ? PaymentStatus.processed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    growing: null;
} | {
    harvesting: null;
} | {
    planting: null;
}): Stage {
    return "growing" in value ? Stage.growing : "harvesting" in value ? Stage.harvesting : "planting" in value ? Stage.planting : value;
}
function from_candid_variant_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    saved: null;
} | {
    generated: null;
}): ReportStatus {
    return "saved" in value ? ReportStatus.saved : "generated" in value ? ReportStatus.generated : value;
}
function from_candid_variant_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    soil: null;
} | {
    market: null;
} | {
    fieldActivity: null;
} | {
    yield: null;
}): ReportType {
    return "soil" in value ? ReportType.soil : "market" in value ? ReportType.market : "fieldActivity" in value ? ReportType.fieldActivity : "yield" in value ? ReportType.yield : value;
}
function from_candid_vec_n108(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Crop>): Array<Crop> {
    return value.map((x)=>from_candid_Crop_n61(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n109(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Farm>): Array<Farm> {
    return value.map((x)=>from_candid_Farm_n66(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n110(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryItem>): Array<InventoryItem> {
    return value.map((x)=>from_candid_InventoryItem_n71(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n111(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsArticle>): Array<NewsArticle> {
    return value.map((x)=>from_candid_NewsArticle_n76(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n112(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n83(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n113(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductionCycle>): Array<ProductionCycle> {
    return value.map((x)=>from_candid_ProductionCycle_n88(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n114(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n93(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n115(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SupportRequest>): Array<SupportRequest> {
    return value.map((x)=>from_candid_SupportRequest_n101(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n54(_uploadFile, _downloadFile, x));
}
function to_candid_ArticleStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleStatus): _ArticleStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_Crop_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Crop): _Crop {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_FarmStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FarmStatus): _FarmStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Farm_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Farm): _Farm {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_InventoryItem_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryItem): _InventoryItem {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_InventoryStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryStatus): _InventoryStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_NewsArticle_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsArticle): _NewsArticle {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Payment_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Payment): _Payment {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_ProductionCycle_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductionCycle): _ProductionCycle {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_RegionalFocus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegionalFocus): _RegionalFocus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_ReportStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): _ReportStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_ReportType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportType): _ReportType {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_Report_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Report): _Report {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_Stage_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stage): _Stage {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_SupportPriority_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupportPriority): _SupportPriority {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_SupportRequest_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupportRequest): _SupportRequest {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_SupportStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupportStatus): _SupportStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n116(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    cultivationPractices: string;
    farm: bigint;
    name: string;
    harvestingYields: string;
    lastHarvest?: bigint;
    description: string;
    areaHa: number;
    image?: string;
    pestsDiseases: string;
}): {
    id: bigint;
    cultivationPractices: string;
    farm: bigint;
    name: string;
    harvestingYields: string;
    lastHarvest: [] | [bigint];
    description: string;
    areaHa: number;
    image: [] | [string];
    pestsDiseases: string;
} {
    return {
        id: value.id,
        cultivationPractices: value.cultivationPractices,
        farm: value.farm,
        name: value.name,
        harvestingYields: value.harvestingYields,
        lastHarvest: value.lastHarvest ? candid_some(value.lastHarvest) : candid_none(),
        description: value.description,
        areaHa: value.areaHa,
        image: value.image ? candid_some(value.image) : candid_none(),
        pestsDiseases: value.pestsDiseases
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: FarmStatus;
    manager: string;
    name: string;
    totalAreaHa: number;
    keyCrops: Array<string>;
    location: string;
}): {
    id: bigint;
    status: _FarmStatus;
    manager: string;
    name: string;
    totalAreaHa: number;
    keyCrops: Array<string>;
    location: string;
} {
    return {
        id: value.id,
        status: to_candid_FarmStatus_n16(_uploadFile, _downloadFile, value.status),
        manager: value.manager,
        name: value.name,
        totalAreaHa: value.totalAreaHa,
        keyCrops: value.keyCrops,
        location: value.location
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: InventoryStatus;
    threshold: number;
    name: string;
    unit: string;
    quantity: number;
}): {
    id: bigint;
    status: _InventoryStatus;
    threshold: number;
    name: string;
    unit: string;
    quantity: number;
} {
    return {
        id: value.id,
        status: to_candid_InventoryStatus_n20(_uploadFile, _downloadFile, value.status),
        threshold: value.threshold,
        name: value.name,
        unit: value.unit,
        quantity: value.quantity
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: PaymentStatus;
    date: bigint;
    description: string;
    amount: number;
}): {
    id: bigint;
    status: _PaymentStatus;
    date: bigint;
    description: string;
    amount: number;
} {
    return {
        id: value.id,
        status: to_candid_PaymentStatus_n24(_uploadFile, _downloadFile, value.status),
        date: value.date,
        description: value.description,
        amount: value.amount
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    endDate?: bigint;
    crop: string;
    farmField: string;
    stage: Stage;
    areaHa: number;
    startDate: bigint;
    expectedYield: number;
}): {
    id: bigint;
    status: string;
    endDate: [] | [bigint];
    crop: string;
    farmField: string;
    stage: _Stage;
    areaHa: number;
    startDate: bigint;
    expectedYield: number;
} {
    return {
        id: value.id,
        status: value.status,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        crop: value.crop,
        farmField: value.farmField,
        stage: to_candid_Stage_n28(_uploadFile, _downloadFile, value.stage),
        areaHa: value.areaHa,
        startDate: value.startDate,
        expectedYield: value.expectedYield
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: ReportStatus;
    name: string;
    reportType: ReportType;
    locationFarm: string;
    generatedDate: bigint;
}): {
    id: bigint;
    status: _ReportStatus;
    name: string;
    reportType: _ReportType;
    locationFarm: string;
    generatedDate: bigint;
} {
    return {
        id: value.id,
        status: to_candid_ReportStatus_n32(_uploadFile, _downloadFile, value.status),
        name: value.name,
        reportType: to_candid_ReportType_n34(_uploadFile, _downloadFile, value.reportType),
        locationFarm: value.locationFarm,
        generatedDate: value.generatedDate
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: SupportStatus;
    subject: string;
    createdAt: bigint;
    description: string;
    category: string;
    priority: SupportPriority;
    attachments: Array<string>;
}): {
    id: bigint;
    status: _SupportStatus;
    subject: string;
    createdAt: bigint;
    description: string;
    category: string;
    priority: _SupportPriority;
    attachments: Array<string>;
} {
    return {
        id: value.id,
        status: to_candid_SupportStatus_n38(_uploadFile, _downloadFile, value.status),
        subject: value.subject,
        createdAt: value.createdAt,
        description: value.description,
        category: value.category,
        priority: to_candid_SupportPriority_n40(_uploadFile, _downloadFile, value.priority),
        attachments: value.attachments
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: ArticleStatus;
    featuredOnPage: Array<string>;
    body: string;
    headline: string;
    createdAt: bigint;
    regionalFocus: RegionalFocus;
    tags: Array<string>;
    relatedCrops: Array<string>;
    scheduledPublishDate?: bigint;
    subHeadline: string;
    bannerImage: string;
}): {
    id: bigint;
    status: _ArticleStatus;
    featuredOnPage: Array<string>;
    body: string;
    headline: string;
    createdAt: bigint;
    regionalFocus: _RegionalFocus;
    tags: Array<string>;
    relatedCrops: Array<string>;
    scheduledPublishDate: [] | [bigint];
    subHeadline: string;
    bannerImage: string;
} {
    return {
        id: value.id,
        status: to_candid_ArticleStatus_n46(_uploadFile, _downloadFile, value.status),
        featuredOnPage: value.featuredOnPage,
        body: value.body,
        headline: value.headline,
        createdAt: value.createdAt,
        regionalFocus: to_candid_RegionalFocus_n48(_uploadFile, _downloadFile, value.regionalFocus),
        tags: value.tags,
        relatedCrops: value.relatedCrops,
        scheduledPublishDate: value.scheduledPublishDate ? candid_some(value.scheduledPublishDate) : candid_none(),
        subHeadline: value.subHeadline,
        bannerImage: value.bannerImage
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FarmStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == FarmStatus.active ? {
        active: null
    } : value == FarmStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryStatus): {
    inStock: null;
} | {
    critical: null;
} | {
    lowStock: null;
} {
    return value == InventoryStatus.inStock ? {
        inStock: null
    } : value == InventoryStatus.critical ? {
        critical: null
    } : value == InventoryStatus.lowStock ? {
        lowStock: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    processed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.processed ? {
        processed: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stage): {
    growing: null;
} | {
    harvesting: null;
} | {
    planting: null;
} {
    return value == Stage.growing ? {
        growing: null
    } : value == Stage.harvesting ? {
        harvesting: null
    } : value == Stage.planting ? {
        planting: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): {
    saved: null;
} | {
    generated: null;
} {
    return value == ReportStatus.saved ? {
        saved: null
    } : value == ReportStatus.generated ? {
        generated: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportType): {
    soil: null;
} | {
    market: null;
} | {
    fieldActivity: null;
} | {
    yield: null;
} {
    return value == ReportType.soil ? {
        soil: null
    } : value == ReportType.market ? {
        market: null
    } : value == ReportType.fieldActivity ? {
        fieldActivity: null
    } : value == ReportType.yield ? {
        yield_: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupportStatus): {
    resolved: null;
} | {
    closed: null;
} | {
    open: null;
} | {
    inProgress: null;
} {
    return value == SupportStatus.resolved ? {
        resolved: null
    } : value == SupportStatus.closed ? {
        closed: null
    } : value == SupportStatus.open ? {
        open: null
    } : value == SupportStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupportPriority): {
    important: null;
} | {
    urgent: null;
} {
    return value == SupportPriority.important ? {
        important: null
    } : value == SupportPriority.urgent ? {
        urgent: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleStatus): {
    pendingReview: null;
} | {
    published: null;
} | {
    draft: null;
} {
    return value == ArticleStatus.pendingReview ? {
        pendingReview: null
    } : value == ArticleStatus.published ? {
        published: null
    } : value == ArticleStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegionalFocus): {
    sadc: null;
} | {
    global: null;
} | {
    malawi: null;
} {
    return value == RegionalFocus.sadc ? {
        sadc: null
    } : value == RegionalFocus.global ? {
        global: null
    } : value == RegionalFocus.malawi ? {
        malawi: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
